# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 17:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('sender_eth_id', models.CharField(max_length=42, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 42', regex='^.{42}$')])),
                ('receiver_eth_id', models.CharField(max_length=42, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 42', regex='^.{42}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_address', models.CharField(max_length=42, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 42', regex='^.{42}$')])),
                ('is_read', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('marked_value', models.BooleanField(default=False)),
                ('email_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Email')),
            ],
        ),
    ]
